global:
  scrape_interval:     20s
  evaluation_interval: 10s

scrape_configs:
  - job_name: query_docker_stats
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['host.docker.internal:8001']