{
 "title": "Indexer Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Application Versions",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(coordinator_version) by (Time, coordinator_version)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(proxy_version) by (Time, proxy_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Coordinator Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "coordinator_docker_stats_memory",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "db_docker_stats_memory", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Indexer Proxy Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "proxy_docker_stats_memory", "legendFormat": "__auto" }
   ]
  },
  { "title": "Cpu Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Coordinator Cpu Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "coordinator_docker_stats_cpu", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Postgres Cpu Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "db_docker_stats_cpu", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Indexer Proxy Cpu Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "proxy_docker_stats_cpu", "legendFormat": "__auto" }
   ]
  }
 ]
}